# Change these first
owner: bitpushr # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

# Add your sites here
sites:
  - name: bitpushr Website
    url: https://bitpushr.net
  - name: Plex Media Server
    check: "tcp-ping"
    url: 180.150.55.96
    port: 32400
  - name: Jackett - Query Indexer
    check: "tcp-ping"
    url: 180.150.55.96
    port: 25633
  - name: Overseerr - Media Requester
    check: "tcp-ping"
    url: 180.150.55.96
    port: 5055
  - name: Radarr - Media Finder
    check: "tcp-ping"
    url: 180.150.55.96
    port: 7878
  - name: Sonarr - Media Finder
    check: "tcp-ping"
    url: 180.150.55.96
    port: 8989
  - name: Tautulli - PMS Monitoring
    check: "tcp-ping"
    url: 	180.150.55.96
    port: 8181
  - name: NextDNS Instance - Melb, AU
    check: "tcp-ping"
    url: 45.90.28.66
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.bitpushr.net
  baseUrl: /Upptime
  logoUrl: https://i.imgur.com/7heSCRL.png
  name: Upptime
  introTitle: "bitpushr's Homelab Status"
  introMessage: This status page shows how my services are performing live. It also explains reasons for downtime, if any.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
